---
pidfile_directory: .robot_sweatshop/run
logfile_directory: .robot_sweatshop/log
job_directory: .robot_sweatshop/jobs
workspace_directory: .robot_sweatshop/workspaces
moneta_directory: .robot_sweatshop/db
# user: ci-bot
# group: nogroup
http_port: 8080
http_bind: 0.0.0.0
# queue_handler_port: 5556
# queue_broadcaster_port: 5557
payload_parser_port: 5558
